config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :books
  resources :libraries
  resources :clubs

  get "signup" => "users#new", :as => "signup"
  get "users/:id" => "users#show"
  get "add_book" => "books#new"
  get "books" => "books"
  get "libraries" => "libraries"
  get "add_library" => "libraries#new"
  get "clubs" => "clubs"
  get "add_club" => "clubs#new"

  resources :sessions

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", :as => "logout"

  root 'sessions#new'

  get "/home" => "pages#home", :as => "home"

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Slug

  has_many :books, :autosave => true
  belongs_to :clubs
  has_many :libraries

  accepts_nested_attributes_for :books, :allow_destroy => :true

  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String

  slug :email, history: true

  validates :email, :presence => { :message => "You must provide an email."}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_user, :only => [:create, :new]

  def books
    @books = @user.books
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
    @user.books.build
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/views/users/_form.html.erb
<%= nested_form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %><br><br>
  </div>
  <%= f.fields_for :books do |book_form| %>
    <%= book_form.label :book %><br>
    <%= book_form.label :title %><br>
    <%= book_form.text_field :title %><br>
    <%= book_form.label :author %><br>
    <%= book_form.text_field :author %><br>
    <%= book_form.label :isbn %><br>
    <%= book_form.text_field :isbn %><br>
    <%= book_form.label :description %><br>
    <%= book_form.text_field :description %><br>
    <%= book_form.link_to_remove "Remove this book" %>
  <% end %>
<p><%= f.link_to_add "Add a book", :books %></p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <% if user.email == @current_user.email %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong><br>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong><br>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong><br>
  <%= @user.email %>
</p>
<p>
  <strong>Books:</strong><br>
  <% @user.books.each do |book| %>
  	<%= book.title %><br>
  	<%= book.author %><br>
  	<%= book.isbn %><br>
  	<%= book.description %><br>
  <% end %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>